apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: examples.conversion.example.com
  ownerReferences:
    - apiVersion: pkg.crossplane.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: ProviderRevision
      name: example-provider-revision-12345
      uid: PLACEHOLDER_UID
spec:
  group: conversion.example.com
  versions:
    - name: v1
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                field1:
                  type: string
            status:
              type: object
    - name: v2
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                field1:
                  type: string
                field2:
                  type: string
            status:
              type: object
  scope: Namespaced
  names:
    plural: examples
    singular: example
    kind: Example
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: conversion-webhook-service
          namespace: webhook-system
          path: /convert
        caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lVTDJyVjVIVE9lSWJGczdlR3VEVnFHd3ZKVElNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0xURUxNQWtHQTFVRUJoTUNRMEV4RGpBTUJnTlZCQWdNQlZCeWIzWnBNUkF3RGdZRFZRUUtEQWRGZUdGdApjR3hsTUI0WERUSTFNRGN3TnpJeU1URXlObG9YRFRJMU1EZ3dOakl5MVRGME5sb3dMVEVMTUFrR0ExVUVCaE1DClEwRXhEakFNQmdOVkJBZ01CVkJ5YjNacE1SQXdEZ1lEVlFRS0RBZEZlR0Z0Y0d4bE1JSUJJakFOQmdrcWhraUcKOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXNlWVFmWTdCRGhwSGRnRGsrNk1JbWowZStOSzFzVGdqL3ZqTgpkZlVmTHhEZnVlRWZPUVVmcW9YYVpEbjhISlZsR3pIT3NsUWExQnJUaW5JdjJuZ2pjRmgzUTlqTmh2S0lqU3VyCktJRUxldk5jRk4xcDRqNi80Y0k2U3RhbEppaG14ZUNHWXVNVVpXYWk0ZlBHdEpWdFd0R1NoSk9HRW1vcktoTGwKb2JrN1NjYjdxeTNiVWZ3ZkFWWWNYZjFVSnQ5dnpnYTUrK3I0V0dFM0JDajlQdWpscDNlTUNCN0x0VmIxRXNOZAovNk1YTzVGMElQcDFZUFl6UjBHbldsVmQ4VXZsWWZ1M25hMk1OVjVDcDVzZlFNNGZKbWJlL0RzWHMycFVBQWxOCkFVQ1RzYXpEUlBXQUFBSllNVzB2MHVCMG9icW5NVExPUEdHNTNOVWlpQUl0VXdJREFRQUJvMU13VVRBZEJnTlYKSFE0RUZnUVVxMnB5K0EyWXE5ZC9IbGE2MEtLYWE3VDN4bjh3SHdZRFZSMGpCQmd3Rm9BVXEycHkrQTJZcTlkLwpIbGE2MEtLYWE3VDN4bjh3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBCnNyQ0VNOVVSK1ViREkvS2llUUhVT05zQzF4ZjdHZkNxYWlhS1EveFc5NERjTnhETkQvekRFdGJqWi82dzY2ODEKT0JsL0lWMlE5M3BmclZoTFNINDhObmNLOC8vTFZzQ3pkRlVYMzZYKzNLODFDOEJ1VzB0Y1BXYlVtU1NsWkJBVQowMjhvSVVOYnFWUmVlTGk4T29EMTgvRmtIdHJ2RUEyM2drS01lUHJqUlMvQ2NPdE1rV2pKNGFCUWltUTBDSTEzCmxCd0pOODRoN3VZLzdKUmkycVhvYjNKblAremV1VnFBTTVSeUlyZCt5RlpVNkl1Z2JXaUl2elVvUnZPNzRCMDEKbEpGd2pRc2gvaXhoWW15Q1pXWk43TkVvUmI1V2d5UUVJNlI3NnVYdXRuWTNYTm4zWnhUOTRKQi9RSWhSNEEzSwo5KzNsaTFvN0JGZnZQZE55YUVva2JRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      conversionReviewVersions:
        - v1
        - v1beta1
