apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: examples.conversion.example.com
spec:
  group: conversion.example.com
  versions:
    - name: v1
      served: true
      storage: true  # v1 is the storage version initially
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                field1:
                  type: string
            status:
              type: object
    - name: v2
      served: true
      storage: false  # v2 is served but not storage
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                field1:
                  type: string
            status:
              type: object
  scope: Namespaced
  names:
    plural: examples
    singular: example
    kind: Example
  # Note: NO conversion section initially - this allows multiple API versions
  # without requiring webhooks since they're schema-compatible
