apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: providerrevisions.pkg.crossplane.io
spec:
  group: pkg.crossplane.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                package:
                  type: string
                revision:
                  type: integer
                desiredState:
                  type: string
                  enum: ["Active", "Inactive"]
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
                controllerRef:
                  type: object
                  properties:
                    name:
                      type: string
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: providerrevisions
    singular: providerrevision
    kind: ProviderRevision
    shortNames:
      - pr
